#!/usr/bin/env python3
"""
Golden-file snapshot tests for scripts/build.py.

WHY THIS FILE EXISTS
--------------------
build.py is ~3,900 lines and is the entire CMS: frontmatter parsing, the
family/stack-level models, see_also resolution, backlinks, the atlas grid,
the scatter geometry, the SVG dependency graph, eleven page generators, the
search index, the sitemap, RSS, llms.txt and the CLI dataset. Eight closed
bugs lived in it, and every one of them was found by a human reading the
rendered site. A snapshot of the rendered site is therefore the oracle that
matches how the defects actually present.

WHAT IT ASSERTS
---------------
  1. Golden snapshot. A small fixture corpus (tests/fixtures/content) is
     built into a temp directory and every generated byte is compared against
     tests/golden/. Any rendering change shows up as a reviewable diff.
  2. Determinism. The same corpus built twice must be byte-identical. This is
     the single most valuable assertion here: it is the property most likely
     to regress silently (a dict iteration order, a wall clock, a set) and it
     was hard-won in #91.
  3. Gates. A corpus with a bad family slug, an unresolvable see_also or an
     unknown stack_level must fail the build AND write zero files. A gate
     that runs after promotion is a post-mortem, not a gate.
  4. Escaping, page structure, JSON-LD validity, and CLI/web dataset parity.

ISOLATION
---------
Everything the build writes through is a module-level path constant in
observatory.config, so the sandbox below repoints all of them at a temp
directory:

    config.CONTENT_DIR      fixture corpus, not content/
    config.OUTPUT_DIR       temp dir, not the repo root
    config.SITE_ROOT        nonexistent temp path, so no committed OG card is
                            found and no git history is consulted
    config.FIRST_SEEN_PATH  temp file, not the committed scripts/first_seen.json
    export_cli_data.OUT_PATHS  temp file + the sandbox output, not the
                            committed cli/data/sensors.json
    gen_og.generate         stubbed to its documented browser-absent result,
                            because the real one drives headless Chromium and
                            DELETES committed og/cards/*.png for any sensor
                            not in the corpus it is handed

The runner additionally fingerprints the repo's own generated tree before and
after the suite and fails if a single byte moved. Tests that dirty the tree
they are meant to protect are worse than no tests.

USAGE
    .venv/bin/python scripts/test_build.py            # run the suite
    .venv/bin/python scripts/test_build.py --update   # re-bless the goldens
    make test

Re-bless goldens in the SAME commit as the rendering change that caused them
to move, and read the diff — it is the review artifact.
"""

import contextlib
import difflib
import hashlib
import io
import json
import re
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

import build            # noqa: E402
import export_cli_data  # noqa: E402
import gen_og           # noqa: E402
from observatory import config, dates  # noqa: E402

FIXTURE_CONTENT = REPO_ROOT / "tests" / "fixtures" / "content"
GOLDEN_DIR = REPO_ROOT / "tests" / "golden"

# Files the real build owns that a leaky test would clobber. Checked before and
# after the whole suite; see verify_repo_untouched().
GUARDED_PATHS = (
    "cli/data/sensors.json",
    "scripts/first_seen.json",
    "og/manifest.json",
    "sensors.json",
    "index.html",
    "search-index.json",
    "sitemap.xml",
    "rss.xml",
    "llms.txt",
    "llms-full.txt",
    "404.html",
    "robots.txt",
)
GUARDED_DIRS = ("og/cards", "sensors", "catalog", "families", "atlas", "md")


# ── Sandbox ─────────────────────────────────────────────────────────────────

class Sandbox:
    """A build of `content_dir` into a throwaway tree, with every module-level
    path in observatory.config / export_cli_data.py / gen_og.py repointed at
    it."""

    def __init__(self, content_dir=FIXTURE_CONTENT):
        self.content_dir = Path(content_dir)
        self.tmp = None
        self.out = None
        self.log = ""

    def __enter__(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="so-build-test-"))
        self.out = self.tmp / "site"
        self.out.mkdir()
        (self.tmp / "cli" / "data").mkdir(parents=True)

        self._saved = {
            (config, "CONTENT_DIR"): config.CONTENT_DIR,
            (config, "OUTPUT_DIR"): config.OUTPUT_DIR,
            (config, "SITE_ROOT"): config.SITE_ROOT,
            (config, "FIRST_SEEN_PATH"): config.FIRST_SEEN_PATH,
            (dates, "_git_first_seen"): dates._git_first_seen,
            (export_cli_data, "OUT_PATHS"): export_cli_data.OUT_PATHS,
            (gen_og, "generate"): gen_og.generate,
            (gen_og, "OG_DIR"): gen_og.OG_DIR,
            (gen_og, "MANIFEST_PATH"): gen_og.MANIFEST_PATH,
        }

        config.CONTENT_DIR = self.content_dir
        config.OUTPUT_DIR = self.out
        # Nonexistent on purpose: sensor_og_image() then finds no committed
        # card, so og:image is the site-wide fallback and the snapshot does not
        # depend on which PNGs happen to be checked in.
        config.SITE_ROOT = self.tmp / "no-such-repo"
        config.FIRST_SEEN_PATH = self.tmp / "first_seen.json"
        # A fixture corpus has no git history; asking the real repo for one
        # would make the golden output a function of the checkout.
        dates._git_first_seen = lambda: {}

        # The CLI copy goes to the sandbox (it is committed in the real repo);
        # the web copy lands in the snapshotted tree, where it belongs.
        self.cli_json = self.tmp / "cli" / "data" / "sensors.json"
        export_cli_data.OUT_PATHS = (str(self.cli_json), str(self.out / "sensors.json"))

        gen_og.OG_DIR = self.tmp / "og" / "cards"
        gen_og.MANIFEST_PATH = self.tmp / "og" / "manifest.json"
        gen_og.generate = _stub_gen_og

        return self

    def __exit__(self, *exc):
        for (module, name), value in self._saved.items():
            setattr(module, name, value)
        shutil.rmtree(self.tmp, ignore_errors=True)
        return False

    def run(self, check_only=False):
        """Run the build. Returns the captured stdout; raises what build raises."""
        buf = io.StringIO()
        try:
            with contextlib.redirect_stdout(buf):
                build.main(check_only=check_only)
        finally:
            self.log = buf.getvalue()
        return self.log

    def tree(self):
        return read_tree(self.out)


def _stub_gen_og(items, force=False, quiet=False):
    """gen_og.generate()'s documented browser-absent result.

    The real function drives headless Chromium (slow, and not a build
    requirement) and, worse for a test, deletes og/cards/<slug>.png for every
    slug not in `items` — pointed at a five-entry fixture corpus it would wipe
    the committed cards for the whole real catalog.
    """
    return {"written": 0, "skipped": len(items), "removed": 0,
            "error": "gen_og stubbed by scripts/test_build.py"}


# ── Tree helpers ────────────────────────────────────────────────────────────

def read_tree(root):
    """{posix relative path: bytes} for every file under `root`."""
    root = Path(root)
    return {
        str(p.relative_to(root).as_posix()): p.read_bytes()
        for p in sorted(root.rglob("*")) if p.is_file()
    }


def diff_trees(expected, actual, expected_label="golden", actual_label="built",
               max_files=8, max_lines=40):
    """Human-readable report of the difference between two {path: bytes} maps."""
    problems = []
    missing = sorted(set(expected) - set(actual))
    extra = sorted(set(actual) - set(expected))
    if missing:
        problems.append(f"{len(missing)} file(s) in {expected_label} but not "
                        f"{actual_label}: {', '.join(missing[:20])}")
    if extra:
        problems.append(f"{len(extra)} file(s) in {actual_label} but not "
                        f"{expected_label}: {', '.join(extra[:20])}")

    changed = [p for p in sorted(set(expected) & set(actual))
               if expected[p] != actual[p]]
    if changed:
        problems.append(f"{len(changed)} file(s) differ: "
                        f"{', '.join(changed[:20])}")
    for path in changed[:max_files]:
        try:
            before = expected[path].decode("utf-8").splitlines(keepends=True)
            after = actual[path].decode("utf-8").splitlines(keepends=True)
        except UnicodeDecodeError:
            problems.append(f"  {path}: binary content differs")
            continue
        delta = list(difflib.unified_diff(
            before, after, fromfile=f"{expected_label}/{path}",
            tofile=f"{actual_label}/{path}", n=1))
        problems.append("".join(delta[:max_lines]).rstrip())
        if len(delta) > max_lines:
            problems.append(f"  ... ({len(delta) - max_lines} more diff lines)")
    return "\n".join(problems)


def fingerprint_repo():
    """sha256 per guarded real-repo path, so a leak is provable, not assumed."""
    prints = {}
    for rel in GUARDED_PATHS:
        p = REPO_ROOT / rel
        prints[rel] = hashlib.sha256(p.read_bytes()).hexdigest() if p.is_file() else "<absent>"
    for rel in GUARDED_DIRS:
        d = REPO_ROOT / rel
        h = hashlib.sha256()
        for f in sorted(d.rglob("*")) if d.is_dir() else []:
            if f.is_file():
                h.update(str(f.relative_to(REPO_ROOT)).encode())
                h.update(hashlib.sha256(f.read_bytes()).digest())
        prints[rel + "/"] = h.hexdigest() if d.is_dir() else "<absent>"
    return prints


HTML_SUFFIX = ".html"


def html_files(tree):
    return {p: b for p, b in tree.items() if p.endswith(HTML_SUFFIX)}


class PageAssertions(unittest.TestCase):
    """assertIn() on a 30 KB page dumps the entire page into the failure
    report and buries the message. These say what was wrong instead."""

    def assertInPage(self, needle, page, label):
        self.assertTrue(needle in page, f"{label}: expected to find {needle!r}")

    def assertNotInPage(self, needle, page, label):
        self.assertTrue(needle not in page, f"{label}: unexpectedly found {needle!r}")


# ── Shared build ────────────────────────────────────────────────────────────
# One build of the good corpus, reused by every test that only reads output.

_BUILT = {}


def built_tree():
    if "tree" not in _BUILT:
        with Sandbox() as sb:
            sb.run()
            _BUILT["tree"] = sb.tree()
            _BUILT["log"] = sb.log
            _BUILT["cli_json"] = sb.cli_json.read_bytes()
    return _BUILT["tree"]


# ── Tests ───────────────────────────────────────────────────────────────────

class TestGoldenSnapshot(unittest.TestCase):
    """The fixture corpus renders exactly what is committed under tests/golden."""

    def test_matches_golden(self):
        self.assertTrue(
            GOLDEN_DIR.is_dir(),
            f"{GOLDEN_DIR} does not exist. Create it with:\n"
            f"  .venv/bin/python scripts/test_build.py --update",
        )
        golden = read_tree(GOLDEN_DIR)
        actual = built_tree()
        if golden != actual:
            self.fail(
                "Generated output does not match tests/golden/.\n\n"
                + diff_trees(golden, actual)
                + "\n\nIf this change is intentional, re-bless the goldens in "
                  "the SAME commit:\n"
                  "  .venv/bin/python scripts/test_build.py --update\n"
                  "and read the resulting diff — it is the review artifact."
            )

    def test_golden_is_not_empty(self):
        # A golden dir that got wiped would make the comparison above pass
        # vacuously against an equally-wiped build.
        golden = read_tree(GOLDEN_DIR)
        self.assertGreater(len(golden), 20, "tests/golden/ looks truncated")
        for required in ("index.html", "sensors/alpha-probe/index.html",
                         "families/structural/index.html", "atlas/index.html",
                         "search-index.json", "sitemap.xml", "rss.xml",
                         "llms.txt", "llms-full.txt", "sensors.json",
                         "md/sensors/alpha-probe.md"):
            self.assertIn(required, golden)


class TestDeterminism(unittest.TestCase):
    """Two builds of the same corpus must be byte-identical.

    #91 was a wall clock leaking into generated output, which dirtied the
    working tree on every build. This is the assertion that would have caught
    it, and the one a future contributor is most likely to break: any dict
    ordered by iteration, any set rendered in place, any datetime.now().
    """

    def test_two_builds_are_byte_identical(self):
        with Sandbox() as first:
            first.run()
            tree_a = first.tree()
        with Sandbox() as second:
            second.run()
            tree_b = second.tree()

        self.assertTrue(tree_a, "first build produced nothing")
        if tree_a != tree_b:
            self.fail(
                "BUILD IS NOT DETERMINISTIC: two builds of the same content "
                "produced different output.\n\n"
                + diff_trees(tree_a, tree_b, "build-1", "build-2")
                + "\n\nSomething in build.py depends on the wall clock, on "
                  "iteration order, or on state left behind by the previous "
                  "run. See #91."
            )


class TestGates(unittest.TestCase):
    """Each gate must fail the build, say something useful, and write nothing."""

    def _run_bad_corpus(self, filename, replacements):
        """Copy the fixture corpus, mutate one file, build, return (exc, tree)."""
        with tempfile.TemporaryDirectory(prefix="so-bad-corpus-") as bad_root:
            bad_content = Path(bad_root) / "content"
            shutil.copytree(FIXTURE_CONTENT, bad_content)
            target = bad_content / "sensors" / filename
            text = target.read_text(encoding="utf-8")
            for old, new in replacements:
                self.assertIn(old, text, f"fixture drifted: {old!r} not in {filename}")
                text = text.replace(old, new, 1)
            target.write_text(text, encoding="utf-8")

            with Sandbox(bad_content) as sb:
                with self.assertRaises(AssertionError) as caught:
                    sb.run()
                return str(caught.exception), read_tree(sb.out)

    def test_bad_family_slug_fails_and_writes_nothing(self):
        message, tree = self._run_bad_corpus(
            "alpha-probe.md", [("family: structural", "family: strucutral")])
        self.assertIn("Unrecognized family/stack_level slugs", message)
        self.assertIn("strucutral", message)
        self.assertIn("Valid families:", message,
                      "the gate must name the valid values, not just complain")
        self.assertEqual(tree, {}, f"gate wrote files before failing: {sorted(tree)}")

    def test_unknown_stack_level_fails_and_writes_nothing(self):
        message, tree = self._run_bad_corpus(
            "beta-signal.md", [("stack_level: behavioral-tests",
                                "stack_level: behavioural-tests")])
        self.assertIn("Unrecognized family/stack_level slugs", message)
        self.assertIn("behavioural-tests", message)
        self.assertIn("Valid stack levels:", message)
        self.assertEqual(tree, {}, f"gate wrote files before failing: {sorted(tree)}")

    def test_unresolvable_see_also_fails_and_writes_nothing(self):
        message, tree = self._run_bad_corpus(
            "alpha-probe.md", [("- SO-T02", "- SO-T02\n- SO-NOPE")])
        self.assertIn("Unresolved see_also tokens", message)
        self.assertIn("SO-NOPE", message)
        self.assertIn("must be a sensor ID, a family slug, or the literal 'atlas'",
                      message)
        self.assertEqual(tree, {}, f"gate wrote files before failing: {sorted(tree)}")

    def test_check_only_validates_and_writes_nothing(self):
        with Sandbox() as sb:
            log = sb.run(check_only=True)
            self.assertIn("wrote nothing", log)
            self.assertEqual(read_tree(sb.out), {})


class TestEscaping(PageAssertions):
    """A hostile title must be entity-encoded everywhere it is rendered.

    tests/fixtures/content/sensors/delta-escape.md is titled
    `Delta & </script><img src=x onerror=alert(1)>` precisely so this is
    checked by a machine on every run instead of by a human during an audit.
    """

    RAW = "</script><img src=x onerror=alert(1)>"

    def test_raw_payload_never_reaches_generated_html(self):
        offenders = []
        for path, data in html_files(built_tree()).items():
            if self.RAW in data.decode("utf-8"):
                offenders.append(path)
        self.assertEqual(offenders, [],
                         f"unescaped script-closing payload in: {offenders}")

    def test_rss_escapes_the_payload(self):
        rss = built_tree()["rss.xml"].decode("utf-8")
        self.assertNotInPage(self.RAW, rss, "rss.xml")
        self.assertInPage("&lt;/script&gt;", rss, "rss.xml")

    def test_search_index_carries_the_payload_as_json_data_only(self):
        """search-index.json legitimately holds the raw title.

        It is a JSON document fetched by js/main.js and rendered through
        textContent (see the comment at js/main.js:140), never inlined into a
        page and never assigned to innerHTML. Escaping it here would double-
        encode the search results. What must hold is that it is a well-formed
        JSON string and that no HTML page ever inlines it.
        """
        entries = json.loads(built_tree()["search-index.json"])
        titles = [e["title"] for e in entries]
        self.assertIn("Delta & " + self.RAW, titles)

        # The claim above is only true while the consumer keeps its side of
        # the bargain, so assert that too rather than trusting a comment.
        client = (REPO_ROOT / "js" / "main.js").read_text(encoding="utf-8")
        self.assertIn("textContent = str(item.title)", client)
        self.assertNotIn("innerHTML = str(item", client)
        self.assertNotIn("innerHTML = item", client)

    def test_payload_is_present_but_encoded(self):
        page = built_tree()["sensors/delta-escape/index.html"].decode("utf-8")
        self.assertInPage("&lt;/script&gt;&lt;img src=x onerror=alert(1)&gt;",
                          page, "delta-escape page")
        self.assertInPage("Delta &amp; ", page, "delta-escape page")

    def test_json_ld_escapes_angle_brackets(self):
        # json_ld_script() replaces "<" with \u003c so no content can close the
        # surrounding <script> element even if it parses as valid JSON.
        page = built_tree()["sensors/delta-escape/index.html"].decode("utf-8")
        blocks = build.JSON_LD_RE.findall(page)
        self.assertTrue(blocks, "delta-escape page emits no JSON-LD")
        for block in blocks:
            # No literal "<" at all, so nothing in the payload can close the
            # surrounding element regardless of what else it contains.
            self.assertNotIn("<", block)
        self.assertInPage("\\u003c/script>", page, "delta-escape JSON-LD")


class TestPageStructure(PageAssertions):
    """Cheap structural invariants over every generated page."""

    MAIN_RE = re.compile(r'<main\b[^>]*\bid="main"')
    H1_RE = re.compile(r"<h1\b")

    def test_exactly_one_main_and_one_h1_per_page(self):
        pages = html_files(built_tree())
        self.assertGreater(len(pages), 10, "suspiciously few HTML pages")
        for path, data in sorted(pages.items()):
            text = data.decode("utf-8")
            with self.subTest(page=path):
                self.assertEqual(len(self.MAIN_RE.findall(text)), 1,
                                 f'{path}: expected exactly one <main id="main">')
                self.assertEqual(len(self.H1_RE.findall(text)), 1,
                                 f"{path}: expected exactly one <h1>")

    def test_every_sensor_gets_a_page(self):
        tree = built_tree()
        for slug in ("alpha-probe", "beta-signal", "gamma-unreviewed",
                     "delta-escape", "epsilon-atlas"):
            self.assertIn(f"sensors/{slug}/index.html", tree)

    def test_unreviewed_entry_says_so(self):
        # The honest-provenance path: an absent last_reviewed is reported as
        # absent, never backfilled from something convenient.
        page = built_tree()["sensors/gamma-unreviewed/index.html"].decode("utf-8")
        self.assertInPage('class="review-unreviewed"', page, "gamma-unreviewed page")
        self.assertInPage(">pending</span>", page, "gamma-unreviewed page")
        # The label is about the review, not the entry: an undated page is a
        # finished page, so it must not be dressed up as unfinished or absent.
        self.assertNotInPage("coming soon", page.lower(), "gamma-unreviewed page")
        # And it stays a normal, linkable entry — 563 inbound links across the
        # built site pointed at undated sensors when this was written.
        family = built_tree()["families/behavioral/index.html"].decode("utf-8")
        self.assertInPage('href="/sensors/gamma-unreviewed/"', family,
                          "behavioral family page")
        reviewed = built_tree()["sensors/alpha-probe/index.html"].decode("utf-8")
        self.assertInPage("2025-01", reviewed, "alpha-probe page")
        self.assertNotInPage('class="review-unreviewed"', reviewed, "alpha-probe page")


class TestRenderingBranches(PageAssertions):
    """Assertions on branches the fixtures were written to reach, so that a
    fixture edit that quietly stops reaching them is visible."""

    def test_stale_review_is_flagged(self):
        page = built_tree()["sensors/alpha-probe/index.html"].decode("utf-8")
        self.assertInPage("review-stale-flag", page, "alpha-probe page")
        self.assertInPage("— 13 months ago", page, "alpha-probe page")

    def test_provisional_rating_renders_its_hedge(self):
        page = built_tree()["sensors/delta-escape/index.html"].decode("utf-8")
        self.assertInPage("provisional-note", page, "delta-escape page")
        self.assertInPage("Provisional —", page, "delta-escape page")

    def test_link_rewriting_leaves_the_right_links_alone(self):
        page = built_tree()["sensors/alpha-probe/index.html"].decode("utf-8")
        # Bare filenames become site-absolute directory URLs...
        for href in ('href="/catalog/"', 'href="/sensors/beta-signal/"'):
            self.assertInPage(href, page, "alpha-probe page")
        # ...and everything else is left exactly as authored.
        for href in ('href="https://example.invalid/left-alone"',
                     'href="#references"', 'href="no-such-page.html"'):
            self.assertInPage(href, page, "alpha-probe page")
        # An anchor that already carries a class does not get a second one.
        self.assertNotInPage('class="body-link" class=', page, "alpha-probe page")

    def test_duplicate_headings_get_distinct_ids(self):
        page = built_tree()["sensors/epsilon-atlas/index.html"].decode("utf-8")
        self.assertInPage('id="notes"', page, "epsilon-atlas page")
        self.assertInPage('id="notes-2"', page, "epsilon-atlas page")

    def test_short_first_paragraph_is_not_truncated(self):
        entries = {e["title"]: e for e in
                   json.loads(built_tree()["search-index.json"])}
        blurb = entries["Epsilon Atlas Anchor"]["blurb"]
        self.assertTrue(blurb.endswith("too."), blurb)
        self.assertNotIn("\u2026", blurb)


class TestFrontmatterParsing(unittest.TestCase):
    """parse_frontmatter's degenerate inputs, which no fixture file can carry:
    a sensor file without frontmatter would fail later with a bare KeyError.
    """

    def _parse(self, text):
        with tempfile.TemporaryDirectory(prefix="so-fm-") as d:
            path = Path(d) / "x.md"
            path.write_text(text, encoding="utf-8")
            return build.parse_frontmatter(path)

    def test_file_with_no_frontmatter(self):
        meta, body = self._parse("Just a body.\n")
        self.assertEqual(meta, {})
        self.assertEqual(body, "Just a body.\n")

    def test_file_with_unterminated_frontmatter(self):
        raw = "---\nid: SO-T99\nstill in the block\n"
        meta, body = self._parse(raw)
        self.assertEqual(meta, {})
        self.assertEqual(body, raw)

    def test_empty_frontmatter_block_is_an_empty_dict(self):
        meta, body = self._parse("---\n---\nbody\n")
        self.assertEqual(meta, {})
        self.assertEqual(body, "body")


class TestStructuredData(unittest.TestCase):
    def test_every_json_ld_block_parses(self):
        blocks = 0
        for path, data in sorted(html_files(built_tree()).items()):
            for raw in build.JSON_LD_RE.findall(data.decode("utf-8")):
                blocks += 1
                with self.subTest(page=path):
                    parsed = json.loads(raw)  # raises on invalid JSON-LD
                    self.assertIsInstance(parsed, (dict, list))
        self.assertGreater(blocks, 10, "expected JSON-LD on most pages")

    def test_search_index_and_dataset_parse(self):
        tree = built_tree()
        index = json.loads(tree["search-index.json"])
        dataset = json.loads(tree["sensors.json"])
        self.assertEqual(len(dataset["sensors"]), 5)
        self.assertTrue(index)

    def test_cli_dataset_matches_web_dataset(self):
        # #91 was these two drifting. They are one serialization written twice.
        built_tree()
        self.assertEqual(_BUILT["cli_json"], _BUILT["tree"]["sensors.json"])

    def test_dataset_generated_at_is_derived_from_content(self):
        dataset = json.loads(built_tree()["sensors.json"])
        self.assertEqual(dataset["generated_at"], "2026-03-02T00:00:00Z",
                         "generated_at must come from the newest content date, "
                         "never from the wall clock")


# ── Golden regeneration and the isolation guard ─────────────────────────────

def update_goldens():
    with Sandbox() as sb:
        sb.run()
        if GOLDEN_DIR.exists():
            shutil.rmtree(GOLDEN_DIR)
        shutil.copytree(sb.out, GOLDEN_DIR)
        files = read_tree(GOLDEN_DIR)
    total = sum(len(v) for v in files.values())
    print(f"Re-blessed {len(files)} golden files ({total:,} bytes) in "
          f"{GOLDEN_DIR.relative_to(REPO_ROOT)}/")
    print("Review `git diff tests/golden/` — that diff is the point.")
    return 0


def verify_repo_untouched(before):
    after = fingerprint_repo()
    moved = sorted(k for k in before if before[k] != after.get(k))
    if moved:
        print("\nISOLATION FAILURE: the test suite modified real repo output:",
              file=sys.stderr)
        for path in moved:
            print(f"  {path}", file=sys.stderr)
        return False
    return True


def main(argv):
    if "--update" in argv:
        argv = [a for a in argv if a != "--update"]
        before = fingerprint_repo()
        rc = update_goldens()
        return rc if verify_repo_untouched(before) else 1

    before = fingerprint_repo()
    runner = unittest.main(module=__name__, argv=argv, exit=False,
                           verbosity=2 if "-v" in argv else 1)
    ok = runner.result.wasSuccessful()
    if not verify_repo_untouched(before):
        ok = False
    if ok:
        print("build.py snapshot suite: OK")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
